[codex]
repository = "https://github.com/openai/codex.git"
tag = "rust-v0.155.0-alpha.9.2"
commit = "4607249e430dac1c961df4dc615beae88e33cec8"

[app]
bundle_identifier = "com.openai.codex"
version = "26.915.31945"
build = "9922"
