[codex]
repository = "https://github.com/openai/codex.git"
tag = "rust-v0.155.0-alpha.2.6"
commit = "bf6f0a4ec97919bf697cdc532e7b8af4ec482fc6"

[app]
bundle_identifier = "com.openai.codex"
version = "26.911.61220"
build = "9647"
