[codex]
repository = "https://github.com/openai/codex.git"
tag = "rust-v0.154.0-alpha.6.2"
commit = "b5bffd3ec4db487e7e3dec59663875b0ef7b72ca"

[app]
bundle_identifier = "com.openai.codex"
version = "26.908.40834"
build = "8881"
