// Generated by scripts/project_metadata.py from upstream.toml.

extension CodexCompatibilityContract {
  public static let reference = CodexCompatibilityContract(
    bundleIdentifier: "com.openai.codex",
    appVersion: "26.928.40906",
    appBuild: "12694",
    cliVersion: "codex-cli 0.159.2"
  )
}
