// Generated by scripts/project_metadata.py from upstream.toml.

extension CodexCompatibilityContract {
  public static let supported = CodexCompatibilityContract(
    bundleIdentifier: "com.openai.codex",
    appVersion: "26.917.62051",
    appBuild: "10789",
    cliVersion: "codex-cli 0.155.0-alpha.16.3"
  )
}
