// Generated by scripts/project_metadata.py from upstream.toml.

extension CodexCompatibilityContract {
  public static let reference = CodexCompatibilityContract(
    bundleIdentifier: "com.openai.codex",
    appVersion: "26.924.51851",
    appBuild: "12111",
    cliVersion: "codex-cli 0.158.0-alpha.2.1"
  )
}
