#!/usr/bin/env python3
"""Validate product versions and generate the exact supported Codex contract."""

import argparse
import json
import plistlib
import re
import sys
from pathlib import Path

import tomllib

ROOT = Path(__file__).resolve().parents[1]
GENERATED = Path("app/Sources/CodexTurnrailCore/SupportedCodex.generated.swift")
VERSION = r"(?:0|[1-9][0-9]*)\.(?:0|[1-9][0-9]*)\.(?:0|[1-9][0-9]*)"
PRERELEASE_IDENTIFIER = r"(?:0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*)"
CODEX_VERSION = rf"{VERSION}(?:-{PRERELEASE_IDENTIFIER}(?:\.{PRERELEASE_IDENTIFIER})*)?"


def version_tuple(value):
    if not isinstance(value, str) or re.fullmatch(VERSION, value) is None:
        raise ValueError("A stable major.minor.patch version is required.")
    return tuple(int(part) for part in value.split("."))


def codex_version(tag):
    if not isinstance(tag, str) or re.fullmatch(f"rust-v{CODEX_VERSION}", tag) is None:
        raise ValueError("The Codex base must be an exact rust-v SemVer release tag.")
    return tag[6:]


def codex_version_key(tag):
    version, separator, prerelease = codex_version(tag).partition("-")
    identifiers = (
        tuple(
            (0, int(part)) if part.isdigit() else (1, part)
            for part in prerelease.split(".")
        )
        if separator
        else ()
    )
    return (*version_tuple(version), not separator, identifiers)


def read_upstream(root):
    metadata = tomllib.loads((root / "upstream.toml").read_text())
    fields = {
        "codex": {"repository", "tag", "commit"},
        "app": {"bundle_identifier", "version", "build"},
    }
    if set(metadata) != set(fields):
        raise ValueError("upstream.toml must contain exactly [codex] and [app].")
    for section, keys in fields.items():
        if not isinstance(metadata[section], dict) or set(metadata[section]) != keys:
            raise ValueError(f"Invalid [{section}] fields; required: {sorted(keys)}")
        if any(
            not isinstance(value, str) or not value.strip()
            for value in metadata[section].values()
        ):
            raise ValueError("Upstream metadata values must be nonempty strings.")
    codex, app = metadata["codex"], metadata["app"]
    codex_version(codex["tag"])
    if re.fullmatch(r"[0-9a-f]{40}", codex["commit"]) is None:
        raise ValueError("The Codex base must be a full Git commit SHA.")
    version_tuple(app["version"])
    if re.fullmatch(r"[1-9][0-9]*", app["build"]) is None:
        raise ValueError("The official app build must be a positive integer string.")
    return metadata


def metadata_bytes(metadata):
    return "\n".join(
        f"[{section}]\n"
        + "".join(f"{key} = {json.dumps(value)}\n" for key, value in values.items())
        for section, values in metadata.items()
    ).encode()


def cli_version(metadata):
    return "codex-cli " + codex_version(metadata["codex"]["tag"])


def supported_swift(metadata):
    app = metadata["app"]
    values = [
        app["bundle_identifier"],
        app["version"],
        app["build"],
        cli_version(metadata),
    ]
    bundle, version, build, cli = (json.dumps(value) for value in values)
    return (
        "// Generated by scripts/project_metadata.py from upstream.toml.\n"
        "\n"
        "extension CodexCompatibilityContract {\n"
        "  public static let supported = CodexCompatibilityContract(\n"
        f"    bundleIdentifier: {bundle},\n"
        f"    appVersion: {version},\n"
        f"    appBuild: {build},\n"
        f"    cliVersion: {cli}\n"
        "  )\n"
        "}\n"
    )


def product_version(root):
    info = plistlib.loads((root / "packaging/Info.plist").read_bytes())
    version, build = info["CFBundleShortVersionString"], info["CFBundleVersion"]
    version_tuple(version)
    if not isinstance(build, str) or re.fullmatch(r"[1-9][0-9]*", build) is None:
        raise ValueError("The Turnrail build must be a positive integer string.")
    return version, build


def validate(root, *, tag=None):
    metadata = read_upstream(root)
    if metadata["codex"]["repository"] != "https://github.com/openai/codex.git":
        raise ValueError(
            "Turnrail must pin the official openai/codex source repository."
        )
    version, build = product_version(root)
    if tag is not None and tag != f"v{version}":
        raise ValueError(f"Release tag must be v{version}; received {tag}.")
    cargo = tomllib.loads((root / "engine/codex-rs/Cargo.toml").read_text())
    if cargo["workspace"]["package"]["version"] != metadata["codex"]["tag"][6:]:
        raise ValueError("Engine version does not match the pinned Codex release.")
    if (root / GENERATED).read_text() != supported_swift(metadata):
        raise ValueError("Supported Codex contract is stale; run just metadata-write.")
    return {"version": version, "build": build, "upstream": metadata}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--tag")
    args = parser.parse_args()
    try:
        if args.write:
            (ROOT / GENERATED).write_text(supported_swift(read_upstream(ROOT)))
        print(json.dumps(validate(ROOT, tag=args.tag), indent=2))
    except (OSError, KeyError, TypeError, ValueError) as error:
        print(f"Project metadata is invalid: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
