name: Spelling

on:
  workflow_call:

permissions:
  contents: read

jobs:
  codespell:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: codespell-project/codespell-problem-matcher@b80729f885d32f78a716c2f107b4db1025001c42 # v1.1.0
      - name: Check spelling
        uses: codespell-project/actions-codespell@8f01853be192eb0f849a5c7d721450e7a467c579 # v2.2
        with:
          ignore_words_file: engine/.codespellignore
      - name: Check for a clean worktree
        if: ${{ always() && !cancelled() }}
        uses: ./engine/.github/actions/check-clean-worktree
